Algoritmo "Entrada e Saída de dados"

// Descrição   : Entrada e Saída de dados
// Autor(a)    : Heide
// Data atual  : 27/07/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome:")
   leia(nome)
   escreval("Digite a sua nota:")
   leia(nota)
   
   escreval("O nome digitado foi:", nome)
   escreval("A nota digita foi:", nota)

Fimalgoritmo