Algoritmo "variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleisson Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Heide
// Data atual  : 27/07/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro, nota2: real, nome: caractere, passou: logico;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo